before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - 
    id: "globalping"
    binary: "globalping"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

release:
  disable: true
  skip_upload: true

chocolateys:
  -
    name: globalping

    owners: jsdelivr

    # The app's title.
    # A human-friendly title of the package.
    # Defaults to `ProjectName`.
    title: Globalping CLI

    # Your app's authors (probably you).
    # Defaults are shown below.
    authors: Ayuhito

    # Your app's project url.
    # It is a required field.
    project_url: https://www.jsdelivr.com/globalping

    # App's icon.
    # Default is empty.
    # icon_url: 'https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png'

    license_url: https://github.com/jsdelivr/globalping-cli/blob/master/LICENSE
    project_source_url: https://github.com/jsdelivr/globalping-cli
    docs_url: https://github.com/jsdelivr/globalping-cli/blob/master/README.md
    bug_tracker_url: https://github.com/jsdelivr/globalping-cli/issues

    summary: A global network of probes to run network tests like ping, traceroute and DNS resolve.

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      {{ .ProjectName }} installer package.
      A global network of probes to run network tests like ping, traceroute and DNS resolve.

    release_notes: "https://github.com/jsdelivr/globalping-cli/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_APIKEY }}'
    
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
