before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - 
    id: "globalping"
    binary: "globalping"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

nfpms:
  # note that this is an array of nfpm configs
  -
    package_name: "globalping"
    # Your app's vendor.
    vendor: "Globalping"

    # Template to your app's homepage.
    homepage: "https://globalping.io/"

    # Template to your app's description.
    description: |-
      A global network of probes to run network tests like ping, traceroute and DNS resolve.

    # maintainer
    maintainer: "Ayuhito <hello@ayuhito.com>"

    # Your app's license.
    # Default is empty.
    # license: TBD

    # Formats to be generated.
    formats:
      - deb
      - rpm
      - apk
      - archlinux
      # - termux.deb
      
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
