name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.3"
          cache: true

      - uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.21.3
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN_GORELEASER }}
          CHOCOLATEY_APIKEY: ${{ secrets.CHOCOLATEY_APIKEY }}

      - run: echo ("VERSION_NAME=" + $env:GITHUB_REF_NAME.TrimStart("v")) >> $env:GITHUB_ENV
      - run: echo $VERSION_NAME

      - uses: actions/upload-artifact@v3
        with:
          name: goreleaser-deb
          path: dist/globalping_${{ env.VERSION_NAME }}_linux_amd64.deb
      - uses: actions/upload-artifact@v3
        with:
          name: goreleaser-rpm
          path: dist/globalping_${{ env.VERSION_NAME }}_linux_amd64.rpm
      - uses: actions/upload-artifact@v3
        with:
          name: goreleaser-windows
          path: |
            dist/globalping_Windows_arm64.zip
            dist/globalping_Windows_x86_64.zip
            dist/globalping_Windows_i386.zip

  deploy:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: goreleaser-deb
      - uses: actions/download-artifact@v3
        with:
          name: goreleaser-rpm
      - uses: actions/download-artifact@v3
        with:
          name: goreleaser-windows

      - run: echo "VERSION_NAME=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - run: ls -la

      - name: Release to Packagecloud
        uses: jsdelivr/upload-packagecloud@v3
        with:
          deb-package-name: globalping_${{ env.VERSION_NAME }}_linux_amd64.deb
          rpm-package-name: globalping_${{ env.VERSION_NAME }}_linux_amd64.rpm
          packagecloud-username: jsdelivr
          packagecloud-repo: globalping
          packagecloud-token: ${{ secrets.PACKAGECLOUD_APIKEY }}

      - name: Release to Winget
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: jsdelivr.Globalping
          installers-regex: "Windows_(arm64|x86_64|i386).zip"
          version: ${{ env.VERSION_NAME }}
          max-versions-to-keep: 5
          token: ${{ secrets.GHTOKEN_WINGET }}
