name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
          
      - run: echo ("VERSION_NAME=" + $env:GITHUB_REF_NAME:1) >> $env:GITHUB_ENV
      - run: echo $env:GITHUB_REF_NAME
      - run: echo $env:GITHUB_REF_NAME:1
      - run: echo $env:VERSION_NAME
